name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Bootstrap backend first
      - name: Initialize Terraform (Bootstrap)
        working-directory: ./bootstrap
        run: terraform init

      - name: Apply Terraform (Bootstrap)
        working-directory: ./bootstrap
        run: terraform apply -auto-approve

      # Now run main terraform using the backend created above
      - name: Initialize Terraform (Main)
        run: terraform init
        # Default working directory is root where backend.tf exists

      - name: Validate Terraform (Main)
        run: terraform validate

      - name: Terraform Plan (Main)
        run: terraform plan

      - name: Terraform Apply (Main)
        run: terraform apply -auto-approve

      - name: Export Terraform Output
        run: |
          terraform output -json > terraform_output.json
          aws s3 cp terraform_output.json s3://terraform-artifacts-v2/terraform_output.json

      - name: Generate Resource Manifest
        run: |
          terraform state list > resources.txt
          jq -R -s -c 'split("\n") | map(select(length > 0))' resources.txt > resource-manifest.json
          aws s3 cp resource-manifest.json s3://terraform-artifacts-v2/resource-manifest.json
