name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  bootstrap:
    name: Bootstrap S3 Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bootstrap

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init without backend
        run: terraform init -backend=false

      - name: Apply to create backend bucket
        run: terraform apply -auto-approve

  terraform:
    name: Deploy Terraform Resources
    runs-on: ubuntu-latest
    needs: bootstrap
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init (with backend)
        run: terraform init -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Export Terraform Output to S3
        run: |
          terraform output -json > terraform_output.json
          aws s3 cp terraform_output.json s3://terraform-artifacts-v2/terraform_output.json

      - name: Generate Resource Manifest and Upload to S3
        run: |
          terraform state list > resources.txt
          jq -R -s -c 'split("\n") | map(select(length > 0))' resources.txt > resource-manifest.json
          aws s3 cp resource-manifest.json s3://terraform-artifacts-v2/resource-manifest.json
